version: "3"

services:
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: miyako_dev
    ports:
      - 3306:3306

  # management: http://localhost:15672
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
