version: "3"

services:
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: localhost_dev
      MYSQL_PASSWORD: localhost_dev
      MYSQL_DATABASE: localhost_dev
    ports:
      - 3306:3306

  # management: http://localhost:15672
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  # sqs 실제로 사용되지 않지만 예제 플젝과 동시에 띄울때 필요
  sqs:
    image: softwaremill/elasticmq-native:1.5.2
    ports:
      - "9324:9324"
      - "9325:9325"
