# fly.toml app configuration file generated for miyako-app on 2023-12-10T20:48:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "miyako-app"
primary_region = "nrt"

[build]

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
