service: reijo

useDotenv: true

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs20.x

  region: ap-northeast-1
  stage: dev

  memorySize: 512
  architecture: arm64

  logRetentionInDays: 1
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    STAGE: ${self:provider.stage}
    NODE_ENV: production

    DATABASE_URL: ${env:DATABASE_URL}

package:
  individually: true
  patterns:
    - "!**"
    - "!node_modules/**"

functions:
  httpSite:
    handler: artifact/http_site.dispatch
    url: true
    package:
      patterns:
        - artifact/handlers.mjs*
        - views/**/*
        - static/**/*
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /r/{pathname+}
      - httpApi:
          method: ANY
          path: /robots.txt
      - httpApi:
          method: ANY
          path: /static/{pathname+}

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm artifact
