service: karin-example

useDotenv: true

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs20.x

  region: ap-northeast-1
  stage: dev

  memorySize: 512
  architecture: arm64

  logRetentionInDays: 1
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    AWS_ACCOUNT_ID: ${aws:accountId}

    STAGE: ${self:provider.stage}
    NODE_ENV: production

    REDIS_URL: ${env:REDIS_URL}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - sqs:SendMessage
            - sqs:PurgeQueue
          Resource:
            - arn:aws:sqs:${self:provider.region}:${aws:accountId}:karin-example-${self:provider.stage}

package:
  individually: true
  patterns:
    - "!**"
    - "!node_modules/**"

functions:
  httpMain:
    handler: artifact/http_main.dispatch
    url: true
    package:
      patterns:
        - artifact/http_main.mjs*
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{pathname+}

  sqsMain:
    handler: artifact/sqs_main.dispatch
    package:
      patterns:
        - artifact/sqs_main.mjs*
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:karin-example-${self:provider.stage}
          batchSize: 1
          enabled: false

  websocketConnection:
    handler: artifact/ws_main.handle_connection
    package:
      patterns:
        - artifact/ws_main.mjs*
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  websocketDefault:
    handler: artifact/ws_main.handle_default
    package:
      patterns:
        - artifact/ws_main.mjs*
    events:
      - websocket:
          route: $default

resources:
  Resources:
    SQSExampleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: karin-example-${self:provider.stage}
        VisibilityTimeout: 60
        MessageRetentionPeriod: 1209600 # 14 days

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm artifact
